"use client";

import * as React from "react";
import { Cable } from "lucide-react";
import { ComparisonTable } from "@/components/ComparisonTable";
import type { BrandComparison, CartItem } from "@/lib/types";
import { BUSINESS_NAME, TOOL_NAME } from "@/lib/constants";
import { formatINR, formatToday } from "@/lib/format";

interface QuoteDocumentProps {
  comparisons: BrandComparison[];
  cart: CartItem[];
  bestIdx: number;
  gstMode: 0 | 18;
  expanded: Set<string>;
  onToggle: (brand: string) => void;
}

/**
 * The clean, letterhead-style quote view. This is the DOM node captured for
 * image / PDF export and shown by the print stylesheet (§8).
 */
export const QuoteDocument = React.forwardRef<HTMLDivElement, QuoteDocumentProps>(
  function QuoteDocument(
    { comparisons, cart, bestIdx, gstMode, expanded, onToggle },
    ref
  ) {
    const sortedCart = [...cart].sort((a, b) => a.size - b.size);
    const best = bestIdx >= 0 ? comparisons[bestIdx] : null;

    return (
      <div
        ref={ref}
        className="print-area rounded-lg border bg-white p-5 shadow-sm sm:p-6"
      >
        {/* Letterhead */}
        <div className="flex items-start justify-between gap-4 border-b pb-4">
          <div className="flex items-center gap-3">
            <div className="grid h-11 w-11 place-items-center rounded-lg bg-navy-800 text-white">
              <Cable className="h-6 w-6" />
            </div>
            <div>
              <div className="text-lg font-bold text-navy-800">
                {BUSINESS_NAME}
              </div>
              <div className="text-xs text-muted-foreground">
                {TOOL_NAME} · Brand Comparison Quote
              </div>
            </div>
          </div>
          <div className="text-right text-xs text-muted-foreground">
            <div className="font-medium text-navy-800">Date</div>
            <div>{formatToday()}</div>
          </div>
        </div>

        {/* Order summary */}
        <div className="border-b py-3">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Order (quantities in 90 m units)
          </div>
          {sortedCart.length === 0 ? (
            <div className="text-sm text-muted-foreground">Cart is empty.</div>
          ) : (
            <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm">
              {sortedCart.map((item) => (
                <span key={item.size} className="text-navy-800">
                  <span className="font-semibold">{item.size} sq mm</span>
                  <span className="text-muted-foreground">
                    {" "}
                    × {item.qty} ({item.qty * 90} m)
                  </span>
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Comparison table */}
        <div className="py-4">
          <ComparisonTable
            comparisons={comparisons}
            cart={cart}
            bestIdx={bestIdx}
            gstMode={gstMode}
            expanded={expanded}
            onToggle={onToggle}
          />
        </div>

        {/* Best value callout + GST note */}
        {best && (
          <div className="flex flex-col gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm sm:flex-row sm:items-center sm:justify-between">
            <div className="text-emerald-800">
              <span className="font-semibold">Best value: {best.brand}</span>
              {gstMode === 18 ? (
                <span className="text-emerald-700">
                  {" "}
                  — Subtotal {formatINR(best.gst.subtotal)} · CGST 9%{" "}
                  {formatINR(best.gst.cgst)} · SGST 9% {formatINR(best.gst.sgst)}
                </span>
              ) : null}
            </div>
            <div className="text-lg font-bold text-emerald-700">
              {formatINR(best.gst.total)}
              <span className="ml-1 text-xs font-normal text-emerald-700">
                {gstMode === 18 ? "incl. GST" : "no GST"}
              </span>
            </div>
          </div>
        )}

        <div className="mt-4 border-t pt-3 text-[11px] text-muted-foreground">
          Prices are indicative and computed from the uploaded rate list.
          {gstMode === 18
            ? " GST shown as CGST 9% + SGST 9% (intra-state)."
            : " GST not applied."}{" "}
          Generated by {TOOL_NAME} for {BUSINESS_NAME}.
        </div>
      </div>
    );
  }
);
